name: Run Postman Tests on Windows

on:
  push:
    branches:
      - main

jobs:
  postman-test:
    runs-on: windows-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '22'

    - name: Install Newman & HTML Reporter
      run: npm install -g newman newman-reporter-html

    - name: Run API Tests with Newman
      run: |
        newman run .github/workflows/petst.json -e .github/workflows/environment.json --reporters html --reporter-html-export newman-report.html

    - name: Upload Newman HTML Report
      uses: actions/upload-artifact@v4
      with:
        name: postman-test-report
        path: newman-report.html
